import { DEFAULT_LANGUAGE, type Language } from "../language.js";

export function getAdminCopy(language: Language = DEFAULT_LANGUAGE): AdminCopy {
  return ADMIN_COPY[language];
}

const STATUS_LABELS = {
  "en-US": {
    active: "active",
    disabled: "disabled",
    queued: "queued",
    running: "running",
    completed: "completed",
    failed: "failed",
    cancelled: "cancelled",
    refunded: "refunded",
  },
  "zh-CN": {
    active: "启用",
    disabled: "停用",
    queued: "排队中",
    running: "运行中",
    completed: "已完成",
    failed: "失败",
    cancelled: "已取消",
    refunded: "已退款",
  },
} as const;

const ADMIN_COPY = {
  "en-US": {
    navAriaLabel: "Admin navigation",
    brandSubtitle: "Commercial Ops",
    languageToggleAriaLabel: "切换语言为中文",
    shell: {
      eyebrow: "Platform Control Center",
      badges: {
        commercialMode: "Commercial mode monitored",
        queueBacklog: "Queue Backlog",
        activeWeight: "Active Weight",
        oldest: "Oldest",
        none: "none",
      },
      loading: "Loading live metrics",
      loginRequired: "请先登录管理员账号，再进入商业后台。",
      loginAction: "去登录",
    },
    nav: {
      Overview: "Overview",
      Users: "Users",
      "Access Codes": "Access Codes",
      Credits: "Credits",
      Tasks: "Tasks",
      Queue: "Queue",
      Costs: "Costs",
      Feedback: "Feedback",
      Settings: "Settings",
      "Audit Logs": "Audit Logs",
    },
    status: STATUS_LABELS["en-US"],
    common: {
      manual: "manual",
      none: "none",
      standard: "standard",
      unassigned: "unassigned",
      selectedTaskEmpty: "Select a task to inspect queue and worker transitions.",
    },
    overview: {
      metricsAriaLabel: "Admin metrics",
      metrics: {
        totalUsers: "Total Users",
        redeemedUsers: "Redeemed Users",
        taskCompletion: "Task Completion",
        failureRate: "Failure Rate",
        estimatedCost: "Estimated Cost",
      },
      details: {
        activeDisabled: (active: number, disabled: number) => `${active} active / ${disabled} disabled`,
        codeRedemption: (rate: string) => `${rate} code redemption`,
        completed: (count: number) => `${count} completed`,
        failedTasks: (count: number) => `${count} failed tasks`,
        creditsConsumed: (count: number) => `${count} credits consumed`,
      },
      panels: {
        recentFailures: "Recent Failures",
        highCostTasks: "High Cost Tasks",
        redemptionWatch: "Redemption Watch",
        operatorFocus: "Operator Focus",
        protectPaidExecution: "Protect paid execution",
      },
      table: {
        area: "Area",
        signal: "Signal",
        impact: "Impact",
      },
      signals: {
        tasks: "Tasks",
        queue: "Queue",
        stuckTasks: "Stuck Tasks",
        codes: "Codes",
        failed: (rate: string) => `${rate} failed`,
        backlog: (count: number) => `${count} backlog`,
        stuck: (count: number) => `${count} stuck`,
        disabled: (count: number) => `${count} disabled`,
        taskImpact: "Review provider, worker, and prompt safety errors",
        queueImpact: "Watch capacity before paid users stall",
        stuckImpact: (retrying: number, running: number) => `${retrying} retrying / ${running} running`,
        codeImpact: "Audit campaign shutdowns and partner batches",
      },
      costs: {
        creditsRedeemed: "Credits Redeemed",
        creditsFrozen: "Credits Frozen",
        creditsBalance: "Credits Balance",
        total: (cost: string) => `${cost} total`,
      },
      redemption: {
        active: "Active",
        redeemed: "Redeemed",
        disabled: "Disabled",
        expired: "Expired",
        codes: (count: number) => `${count} codes`,
      },
      miniStats: {
        queued: "Queued",
        running: "Running",
        stuck: "Stuck",
      },
    },
    accessCodes: {
      title: "Access Code Operations",
      description: "Campaign batches, credit grants, tier unlocks, and masked storage controls.",
      tracked: (count: number) => `${count} batches tracked`,
      columns: {
        select: "Select",
        codeMask: "Code Mask",
        batch: "Batch",
        batchName: "Batch Name",
        source: "Source",
        credits: "Credits",
        features: "Features",
        created: "Created",
        redeemed: "Redeemed",
        redemptionRate: "Redemption Rate",
        redeemedUser: "Redeemed User",
        expires: "Expires",
        status: "Status",
        action: "Action",
      },
      actions: {
        disable: "Disable",
        delete: "Delete",
        copyAll: "Copy All",
        bulkAction: "Bulk Action",
        bulkReason: "Bulk reason",
        applyBulk: "Apply to selected codes",
        selected: (count: number) => `${count} selected`,
        bulkUpdated: (count: number) => `${count} codes updated.`,
        selectFirst: "Select at least one code.",
      },
      inventory: {
        title: "Code Inventory",
        description: "Individual masked access codes with per-code disable, delete, and bulk operations.",
        empty: "No individual access codes loaded.",
      },
      batchSummary: "Batch Summary",
      form: {
        title: "Create Campaign Batch",
        campaignName: "Campaign name",
        codeCount: "Code count",
        creditsPerCode: "Credits per code",
        tierGrant: "Tier grant",
        source: "Source",
        features: "Features",
        expiration: "Expiration",
        operatorNotes: "Operator notes",
        submit: "Generate copyable raw codes",
      },
      result: {
        title: "Creation Result",
        empty: "Raw codes appear here only after creation. Stored batch data remains masked.",
        credits: (count: number) => `${count} credits`,
      },
      status: {
        creating: "Creating access-code batch...",
        created: (count: number) => `${count} raw codes generated. Copy them now.`,
        createFailed: (message: string) => `Create failed: ${message}`,
        copied: "Raw codes copied. They will not be reconstructable from storage.",
        disabled: (count: number) => `${count} active codes disabled.`,
      },
    },
    users: {
      metricsAriaLabel: "User operations metrics",
      metrics: {
        activeUsers: "Active Users",
        availableCredits: "Available Credits",
        redeemedBatches: "Redeemed Batches",
        failedTasks: "Failed Tasks",
        disabled: (count: number) => `${count} disabled`,
        frozen: (count: number) => `${count} frozen`,
        campaignSignal: "Campaign conversion signal",
        supportReview: "Needs support review",
      },
      title: "User Operations",
      description: "Accounts, credit health, redemption source, and task reliability.",
      tracked: (count: number) => `${count} users tracked`,
      columns: {
        select: "Select",
        email: "Email",
        status: "Status",
        role: "Role",
        tier: "Tier",
        features: "Features",
        available: "Available",
        frozen: "Frozen",
        redeemedBatches: "Redeemed Batches",
        tasks: "Tasks",
        completed: "Completed",
        failed: "Failed",
        recentActivity: "Recent Activity",
        actions: "Actions",
      },
      empty: "No commercial users loaded.",
      filters: {
        search: "Search email or user ID",
        status: "Status filter",
        allStatuses: "All statuses",
        role: "Role filter",
        allRoles: "All roles",
      },
      actions: {
        create: "Create User",
        edit: "Edit",
        disable: "Disable",
        restore: "Restore",
        delete: "Delete",
        saveEdit: "Save changes",
        bulkTitle: "Bulk Operations",
        bulkOperation: "Bulk operation",
        bulkReason: "Bulk reason",
        applyBulk: "Apply to selected",
        selected: (count: number) => `${count} selected`,
        creating: "Creating user...",
        created: "User created.",
        updating: "Updating user...",
        updated: "User updated.",
        disabled: "User disabled.",
        restored: "User restored.",
        deleted: "User deleted.",
        bulkDone: (count: number) => `${count} users updated.`,
        selectFirst: "Select at least one user.",
      },
      form: {
        email: "Email",
        password: "Temporary password",
        role: "Role",
        tier: "Tier",
        features: "Features",
        initialCredits: "Initial available credits",
        reason: "Reason",
      },
      creditAdjustment: {
        title: "Available Credit Adjustment",
        targetUser: "Target user",
        amount: "Available credit delta",
        idempotencyKey: "Duplicate-prevention operation ID",
        reason: "Reason",
        submit: "Confirm adjustment",
        explanation: "This changes only the user's available credit balance. Frozen credits are shown for context and are not changed here.",
        positiveNegative: "Positive values add credits. Negative values subtract available credits and cannot push the balance below zero.",
        currentAvailable: "Current available",
        frozenContext: "Frozen credits",
        projectedAvailable: "Projected available balance",
        autoGenerated: "Auto-generated if left blank",
        selectUser: "Select a user before adjusting credits.",
        submitting: "Submitting credit adjustment...",
        recorded: (amount: number) => `Credit adjustment recorded: ${amount} credits.`,
      },
      activity: {
        title: "Recent Activity",
        masked: "masked account view",
        lastActivity: "Last activity",
        activeTasks: "Active tasks",
        failureRatio: "Failure ratio",
        notice: "Credit changes must carry a reason and duplicate-prevention operation ID so finance, support, and audit logs can reconcile the operator action.",
      },
    },
    tasks: {
      metricsAriaLabel: "Task operations metrics",
      metrics: {
        activeQueue: "Active Queue",
        failedTasks: "Failed Tasks",
        tokens: "Tokens",
        estimatedCost: "Estimated Cost",
        queuedRunning: "Queued and running",
        errors: "Provider, worker, or validation errors",
        promptCompletion: "Prompt plus completion",
        spend: "Commercial task spend",
      },
      title: "Task Operations",
      description: "Queue latency, worker execution, paid credits, token burn, and failure codes.",
      tracked: (count: number) => `${count} tasks tracked`,
      columns: {
        taskId: "Task ID",
        user: "User",
        scenario: "Scenario",
        mode: "Mode",
        status: "Status",
        queueWait: "Queue Wait",
        runDuration: "Run Duration",
        credits: "Credits",
        tokens: "Tokens",
        cost: "Cost",
        error: "Error",
        worker: "Worker",
      },
      empty: "No commercial tasks loaded.",
      timeline: "Timeline",
      timelineEmpty: "Select a task to inspect queue and worker transitions.",
      stepCost: {
        title: "Step Cost Table",
        hidden: "No prompts or reports exposed",
        step: "Step",
        provider: "Provider",
        model: "Model",
        tokens: "Tokens",
        cost: "Cost",
        status: "Status",
        empty: "Step cost data will appear after worker execution.",
        notice: "Use error codes and step costs together before issuing refunds; avoid exposing raw user prompts or report text in operator views.",
      },
    },
    costs: {
      metricsAriaLabel: "Cost operations metrics",
      metrics: {
        totalEstimatedCost: "Total Estimated Cost",
        provider: "Provider",
        model: "Model",
        step: "Step",
        task: "Task",
        allCalls: "All tracked model calls",
        vendorSplit: "Vendor split",
        modelMix: "Model mix",
        workflowSpend: "Workflow spend",
        highCostTrail: "High-cost task trail",
      },
      title: "Cost Operations",
      description: "Provider, model, step, task, and outcome cost controls for commercial execution.",
      group: {
        provider: "Provider",
        model: "Model",
        step: "Step",
        task: "Task",
        tokens: "Tokens",
        cost: "Cost",
        share: "Share",
        empty: (title: string) => `No ${title.toLowerCase()} cost data loaded.`,
      },
      outcome: {
        title: "Success / Failure",
        watch: "Refund and provider-quality watch",
        column: "Success / Failure",
        empty: "No outcome cost data loaded.",
      },
    },
  },
  "zh-CN": {
    navAriaLabel: "管理后台导航",
    brandSubtitle: "商业运营",
    languageToggleAriaLabel: "Switch language to English",
    shell: {
      eyebrow: "平台控制中心",
      badges: {
        commercialMode: "商业模式监控中",
        queueBacklog: "队列积压",
        activeWeight: "活跃权重",
        oldest: "最早任务",
        none: "无",
      },
      loading: "正在加载实时指标",
      loginRequired: "请先登录管理员账号，再进入商业后台。",
      loginAction: "去登录",
    },
    nav: {
      Overview: "概览",
      Users: "用户",
      "Access Codes": "访问码",
      Credits: "额度",
      Tasks: "任务",
      Queue: "队列",
      Costs: "成本",
      Feedback: "反馈",
      Settings: "设置",
      "Audit Logs": "审计日志",
    },
    status: STATUS_LABELS["zh-CN"],
    common: {
      manual: "手动",
      none: "无",
      standard: "标准",
      unassigned: "未分配",
      selectedTaskEmpty: "选择一个任务查看排队和 worker 流转。",
    },
    overview: {
      metricsAriaLabel: "管理后台指标",
      metrics: {
        totalUsers: "总用户数",
        redeemedUsers: "已兑换用户",
        taskCompletion: "任务完成率",
        failureRate: "失败率",
        estimatedCost: "预估成本",
      },
      details: {
        activeDisabled: (active: number, disabled: number) => `${active} 启用 / ${disabled} 停用`,
        codeRedemption: (rate: string) => `${rate} 访问码兑换率`,
        completed: (count: number) => `${count} 个已完成`,
        failedTasks: (count: number) => `${count} 个失败任务`,
        creditsConsumed: (count: number) => `${count} 额度已消耗`,
      },
      panels: {
        recentFailures: "近期失败",
        highCostTasks: "高成本任务",
        redemptionWatch: "兑换监控",
        operatorFocus: "运营重点",
        protectPaidExecution: "保护付费执行",
      },
      table: {
        area: "区域",
        signal: "信号",
        impact: "影响",
      },
      signals: {
        tasks: "任务",
        queue: "队列",
        stuckTasks: "卡住任务",
        codes: "访问码",
        failed: (rate: string) => `${rate} 失败`,
        backlog: (count: number) => `${count} 积压`,
        stuck: (count: number) => `${count} 卡住`,
        disabled: (count: number) => `${count} 停用`,
        taskImpact: "检查供应商、worker 和提示词安全错误",
        queueImpact: "在付费用户停滞前观察容量",
        stuckImpact: (retrying: number, running: number) => `${retrying} 重试中 / ${running} 运行中`,
        codeImpact: "审计活动关停和合作批次",
      },
      costs: {
        creditsRedeemed: "已兑换额度",
        creditsFrozen: "冻结额度",
        creditsBalance: "额度余额",
        total: (cost: string) => `${cost} 合计`,
      },
      redemption: {
        active: "启用",
        redeemed: "已兑换",
        disabled: "停用",
        expired: "已过期",
        codes: (count: number) => `${count} 个访问码`,
      },
      miniStats: {
        queued: "排队中",
        running: "运行中",
        stuck: "卡住",
      },
    },
    accessCodes: {
      title: "访问码运营",
      description: "活动批次、额度发放、等级解锁和脱敏存储控制。",
      tracked: (count: number) => `已跟踪 ${count} 个批次`,
      columns: {
        select: "选择",
        codeMask: "卡密码",
        batch: "批次",
        batchName: "批次名称",
        source: "来源",
        credits: "额度",
        features: "权益",
        created: "创建时间",
        redeemed: "已兑换",
        redemptionRate: "兑换率",
        redeemedUser: "兑换用户",
        expires: "过期时间",
        status: "状态",
        action: "操作",
      },
      actions: {
        disable: "禁用",
        delete: "删除",
        copyAll: "复制全部",
        bulkAction: "批量动作",
        bulkReason: "批量原因",
        applyBulk: "应用到选中卡密",
        selected: (count: number) => `已选择 ${count} 个`,
        bulkUpdated: (count: number) => `已更新 ${count} 个卡密。`,
        selectFirst: "请至少选择一个卡密。",
      },
      inventory: {
        title: "单码库存",
        description: "每个脱敏卡密的禁用、删除和批量操作。",
        empty: "暂无单个访问码数据。",
      },
      batchSummary: "批次汇总",
      form: {
        title: "生成活动批次",
        campaignName: "活动名称",
        codeCount: "码数量",
        creditsPerCode: "每码额度",
        tierGrant: "等级发放",
        source: "来源",
        features: "权益",
        expiration: "过期时间",
        operatorNotes: "运营备注",
        submit: "生成可复制原始码",
      },
      result: {
        title: "创建结果",
        empty: "原始码只会在创建后显示在这里。存储中的批次数据保持脱敏。",
        credits: (count: number) => `${count} 额度`,
      },
      status: {
        creating: "正在创建访问码批次...",
        created: (count: number) => `已生成 ${count} 个原始码，请立即复制。`,
        createFailed: (message: string) => `创建失败：${message}`,
        copied: "原始码已复制。存储后无法还原。",
        disabled: (count: number) => `已禁用 ${count} 个启用中的访问码。`,
      },
    },
    users: {
      metricsAriaLabel: "用户运营指标",
      metrics: {
        activeUsers: "启用用户",
        availableCredits: "可用额度",
        redeemedBatches: "已兑换批次",
        failedTasks: "失败任务",
        disabled: (count: number) => `${count} 停用`,
        frozen: (count: number) => `${count} 冻结`,
        campaignSignal: "活动转化信号",
        supportReview: "需要客服复核",
      },
      title: "用户运营",
      description: "账号、额度健康、兑换来源和任务可靠性。",
      tracked: (count: number) => `已跟踪 ${count} 个用户`,
      columns: {
        select: "选择",
        email: "邮箱",
        status: "状态",
        role: "角色",
        tier: "等级",
        features: "权益",
        available: "可用额度",
        frozen: "冻结额度",
        redeemedBatches: "已兑换批次",
        tasks: "任务",
        completed: "已完成",
        failed: "失败",
        recentActivity: "近期活动",
        actions: "操作",
      },
      empty: "暂无商业用户数据。",
      filters: {
        search: "搜索邮箱或用户 ID",
        status: "状态筛选",
        allStatuses: "全部状态",
        role: "角色筛选",
        allRoles: "全部角色",
      },
      actions: {
        create: "创建用户",
        edit: "编辑",
        disable: "封禁",
        restore: "恢复",
        delete: "删除",
        saveEdit: "保存修改",
        bulkTitle: "批量操作",
        bulkOperation: "批量动作",
        bulkReason: "批量原因",
        applyBulk: "应用到选中用户",
        selected: (count: number) => `已选择 ${count} 个`,
        creating: "正在创建用户...",
        created: "用户已创建。",
        updating: "正在更新用户...",
        updated: "用户已更新。",
        disabled: "用户已封禁。",
        restored: "用户已恢复。",
        deleted: "用户已删除。",
        bulkDone: (count: number) => `已更新 ${count} 个用户。`,
        selectFirst: "请至少选择一个用户。",
      },
      form: {
        email: "邮箱",
        password: "临时密码",
        role: "角色",
        tier: "等级",
        features: "权益",
        initialCredits: "初始可用额度",
        reason: "原因",
      },
      creditAdjustment: {
        title: "可用额度调整",
        targetUser: "目标用户",
        amount: "可用额度变更值",
        idempotencyKey: "防重复操作 ID",
        reason: "原因",
        submit: "确认调整",
        explanation: "这里只调整用户的可用额度余额。冻结额度仅作为上下文展示，不会被这个表单直接修改。",
        positiveNegative: "正数增加可用额度，负数扣减可用额度，不能扣成负数。",
        currentAvailable: "当前可用",
        frozenContext: "冻结额度",
        projectedAvailable: "预计可用余额",
        autoGenerated: "留空时自动生成",
        selectUser: "请先选择用户再调整额度。",
        submitting: "正在提交额度调整...",
        recorded: (amount: number) => `额度调整已记录：${amount} 额度。`,
      },
      activity: {
        title: "近期活动",
        masked: "脱敏账号视图",
        lastActivity: "最后活动",
        activeTasks: "活跃任务",
        failureRatio: "失败占比",
        notice: "额度变更必须包含原因和防重复操作 ID，方便财务、客服和审计日志对齐运营操作。",
      },
    },
    tasks: {
      metricsAriaLabel: "任务运营指标",
      metrics: {
        activeQueue: "活跃队列",
        failedTasks: "失败任务",
        tokens: "Token",
        estimatedCost: "预估成本",
        queuedRunning: "排队中和运行中",
        errors: "供应商、worker 或校验错误",
        promptCompletion: "提示词加完成输出",
        spend: "商业任务消耗",
      },
      title: "任务运营",
      description: "队列延迟、worker 执行、付费额度、token 消耗和失败代码。",
      tracked: (count: number) => `已跟踪 ${count} 个任务`,
      columns: {
        taskId: "任务 ID",
        user: "用户",
        scenario: "场景",
        mode: "模式",
        status: "状态",
        queueWait: "排队等待",
        runDuration: "运行时长",
        credits: "额度",
        tokens: "Token",
        cost: "成本",
        error: "错误",
        worker: "Worker",
      },
      empty: "暂无商业任务数据。",
      timeline: "时间线",
      timelineEmpty: "选择一个任务查看排队和 worker 流转。",
      stepCost: {
        title: "步骤成本表",
        hidden: "不暴露提示词或报告正文",
        step: "步骤",
        provider: "供应商",
        model: "模型",
        tokens: "Token",
        cost: "成本",
        status: "状态",
        empty: "worker 执行后会显示步骤成本数据。",
        notice: "退款前请结合错误代码和步骤成本判断；避免在运营视图暴露原始用户提示词或报告正文。",
      },
    },
    costs: {
      metricsAriaLabel: "成本运营指标",
      metrics: {
        totalEstimatedCost: "总预估成本",
        provider: "供应商",
        model: "模型",
        step: "步骤",
        task: "任务",
        allCalls: "所有已跟踪模型调用",
        vendorSplit: "供应商拆分",
        modelMix: "模型组合",
        workflowSpend: "流程消耗",
        highCostTrail: "高成本任务轨迹",
      },
      title: "成本运营",
      description: "按供应商、模型、步骤、任务和结果控制商业执行成本。",
      group: {
        provider: "供应商",
        model: "模型",
        step: "步骤",
        task: "任务",
        tokens: "Token",
        cost: "成本",
        share: "占比",
        empty: (title: string) => `暂无${title}成本数据。`,
      },
      outcome: {
        title: "成功 / 失败",
        watch: "退款和供应商质量观察",
        column: "成功 / 失败",
        empty: "暂无结果成本数据。",
      },
    },
  },
} as const;

export type AdminCopy = (typeof ADMIN_COPY)[Language];
